/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package caw.parkinggaragepos;

//import java.util.Calendar;

/**
 *
 * @author cwojciuk
 */
public class Car {
    
    private double hoursStayed;
    private int carID;
    public Car(double hoursStayed, int carID) {
        timeInGarage(hoursStayed);
    }
    
    public final void timeInGarage(double hoursStayed){
        this.hoursStayed = hoursStayed;
    }
    
    public final double getTimeInGarage(){
        return hoursStayed;
    }
    
    public final int getCarID() {
        return carID;
    }

    public final void setCarID(int carID) {
        this.carID = carID;
    }
    
/*
 * Contains implementation for a more robust Car object that relies on
 * generated time stamps instead of a time generated by a register object.
 * The car would receive a time stamp upon entering and then reference a
 * time stamp when leaving to commit a total time and perform the
 * calculations for the cost.
 * 
 */  
    //private Calendar enterDate;
    
    //public Car(Calendar enterDate, int carID) {
    //  enterGarage(enterDate);
    //}
        
    //public final void enterGarage(Calendar enterDate){
    //  this.enterDate = enterDate;
    //}
    
    //public final Calendar getEnterDate(){
    //  return enterDate;
    //}
    
}
