package caw.parkinggaragepos;

/**
 * caw.parkinggaragepos\Car.java
 * Oct 17, 2012 1:44:04 PM
 * Advanced Java Programming 152-135-10442-13
 * @author Charles Wojciuk
 */

//import java.util.Calendar;
/*
 * This Class represents a Car object that would park inside the parking
 * garage. This class does nothing but represent an object.
 */
public class Car {
    private final String ZEROTIME = "Time in garage must be larger than 0";
    
    private double hoursStayed;
    private int carID;
    
    /**
     * Constructor enforced by the Car class that makes sure the amount of
     * time stayed, and a car ID is passed. Calls the timeInGarage method
     * and the setCarID method which both check for appropriate values.
     * @param hoursStayed
     * @param carID 
     */
    public Car(double hoursStayed, int carID) {
        timeInGarage(hoursStayed);
        setCarID(carID);
    }
    
    public final void timeInGarage(double hoursStayed){
        if(hoursStayed!=0){
            this.hoursStayed = hoursStayed;
        }else{
            throw new IllegalArgumentException(ZEROTIME);
        }
    }
    
    public final double getTimeInGarage(){
        return hoursStayed;
    }
    
    public final int getCarID() {
        return carID;
    }

    public final void setCarID(int carID) {
        //validation required
        this.carID = carID;
    }
    
/*
 * Contains implementation for a more robust Car object that relies on
 * generated time stamps instead of a time generated by a register object.
 * The car would receive a time stamp upon entering and then reference a
 * time stamp when leaving to commit a total time and perform the
 * calculations for the cost.
 * 
 */  
    //private Calendar enterDate;
    
    //public Car(Calendar enterDate, int carID) {
    //  enterGarage(enterDate);
    //}
        
    //public final void enterGarage(Calendar enterDate){
    //  this.enterDate = enterDate;
    //}
    
    //public final Calendar getEnterDate(){
    //  return enterDate;
    //}
    
}
